name: Testing

on:
  pull_request:
    branches: ['**']

jobs:
  pytest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: suvvyai/localtest:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: dev.Dockerfile

      - name: Run tests
        run: docker compose -f docker-compose-test.yml run test
